### ISSUE TITLE
Tracking image is stripped by Core Publisher

### ISSUE THREAD

**Issue by benlk** [Automattic/republication-tracker-tool#73] opened 2020-01-17 19:08 UTC
Reported by Rosemary Hoban, regarding WFAE's site stripping the HTML.

**Comment by joshdarby** [comment] 2020-01-17 19:09
@benlk Wouldn't this be considered a bug/issue on their end? We can't modify how their CMS handles it.

**Comment by benlk** [comment] 2020-01-17 19:13
True, but we may be able to provide specific guidance to Core Publisher users on how to put the content on their site in order to get attribution working.

For example, they may want to use a Web Clip https://nprsupport.desk.com/customer/en/portal/articles/2548980-core-publisher-how-do-i-display-external-content-not-from-npr-or-a-npr-station-on-my-site- to show the content on the Core Publisher site in a way that links directly to the originating website when readers click on the article. It's kinda like a Saved Link in INN's Link Roundups plugin.

**Comment by benlk** [comment] 2020-01-17 19:20
https://nprsupport.desk.com/customer/en/portal/articles/2668335-how-do-i-embed-pym-js-interactive-widgets-using-core-publisher- describes a "source" button that's shown in the screenshots at https://nprsupport.desk.com/customer/en/portal/articles/2606351-core-publisher-adding-an-image-to-a-post for how to add an image, so maybe people can use the "<source>" button to add the image URL?

**Comment by benlk** [comment] 2020-02-14 19:39
And maybe https://www.latimes.com/about/pressreleases/story/2019-07-16/graphene-cms as well

**Comment by adekbadek** [comment] 2021-04-28 15:28
What's Core Publisher?
@benlk could you please provide reproduction steps here?

**Comment by benlk** [comment] 2021-04-29 04:12
[Core Publisher](https://digitalservices.npr.org/topic/core-publisher) is (was?) NPR's CMS for many member sites. It may be being phased out in favor of other CMSes: https://current.org/2019/11/public-media-looks-to-new-cms-for-systemwide-boost-to-web-offerings/

INN was never able to get access to a Core Publisher site to reproduce this error, and most Core Publisher docs were gated behind a login wall for NPR Digital Services customers.

We kept this issue open in the hopes that we'd be able to write better documentation, if it was possible to get the tracking image to stick in Core Publisher.

**Comment by adekbadek** [comment] 2021-04-29 08:09
Thank you for the clarification. I'll close the issue since it's not reproducible at the moment.

**Closed by adekbadek** 2021-04-29 08:09 UTC
Labels: bug, question
